### ISSUE TITLE
"Code Source" field should (probably) be removed for model creation on the web app

### ISSUE THREAD

**Issue by appukuttan-shailesh** [joffreygonin/hbp-validation-framework_dev#106]
The web app currently has a field named "Code Source" for model creation. This requires the URL of the source code. Such a field should probably not exist for the model definition and something similar already exists for the model instance.

**Comment by HFragnaud** [comment]
In fact on the web app, when you define a new model, you also directly define a new model instance. so the name of the model instance and the code source are required.

**Comment by appukuttan-shailesh** [comment]
So that should probably not be the case. We should allow creation of models, without specifying the model instances at the same time. i.e. the model instance should be optional.

**Comment by HFragnaud** [comment]
#114 #115
