### ISSUE TITLE
Validation test view - small changes

### ISSUE THREAD

**Issue by apdavison** [joffreygonin/hbp-validation-framework_dev#128]
### Description tab
- [x] Don't show "Publication" heading if there is no publication
- [x] Don't use scroll bars on the "Test information" box
- [x] Make the "data" fields more prominent, by moving them out of the "Test information" box

### Version tab
- [x] Repository should be a link

### Results tab
- [x] Show fewer significant figures for scores (see #127)
- [x] More whitespace between score and date. Date doesn't need to be clickable.

**Comment by appukuttan-shailesh** [comment]
Just to avoid possible confusion:
"Show fewer significant figures for scores"
- here "figures" refers to the number of digits (i.e. precision) - not the number of graphs, additional files etc, related to the score
