### ISSUE TITLE
Clean up API urls

### ISSUE THREAD

**Issue by apdavison** [joffreygonin/hbp-validation-framework_dev#88]
I propose that the API URLs be modified as follows:

- validationtestdef --> tests
- validationtestscode --> test-instances
- validationresultrest --> results
- validationmodelresultrest2 --> results2
- validationtestalias --> test-aliases
- scientificmodel --> models
- scientificmodelinstance --> model-instances
- scientificmodelimage --> images
- scientificmodelalias --> model-aliases

The rationale for these changes:

- there is a widespread consensus to use plural nouns for REST API resources
- consistent use of "instances" for both tests and models
- "validation" is superfluous since that is the point of the entire framework
- "scientific" is superfluous given the context
- "rest" is superfluous

(It is not clear to me why there are two endpoints for test results. These should be merged if at all possible, but that is for a separate Issue).

**Comment by joffreygonin** [comment]
I totally agree. 
There is two endpoints for results because I created a new version of the result endpoint and the old one is still used in one point by the web-client. This is going to be fixed very soon

**Comment by apdavison** [comment]
changes in cd4f7573b329273957499a11d9b59b30ab768d37
