### ISSUE TITLE
Problem with models when app is deleted

### ISSUE THREAD

**Issue by appukuttan-shailesh** [joffreygonin/hbp-validation-framework_dev#89]
When a model catalog app is deleted from the Collaboratory, the models created with that as the `host app` are retained in the database. If these are set as public (`private`=FALSE), then these apps can still be seen from other model catalog apps. But these models can no longer be edited!

@apdavison : We need to decide how to handle this scenario: If an app is deleted, should the models with that as the host app also be deleted. Probably not. If so, then models access control needs to be changed.

**Comment by apdavison** [comment]
Note that models should be tied to a collab, not to a specific app within that collab.

If a collab is deleted, the models should be retained in the database, but they will no longer be editable.

**Comment by HFragnaud** [comment]
fixed in #81
