### ISSUE TITLE
Test and Model instances with results should not be editable

### ISSUE THREAD

**Issue by appukuttan-shailesh** [joffreygonin/hbp-validation-framework_dev#91]
Users must be forbidden from changing a test instance if there are already results using that test instance.

(Update: Also implement same for model instances)

**Comment by appukuttan-shailesh** [comment]
@apdavison : Should we have a similar restriction on model instances?

**Comment by apdavison** [comment]
Model instances should not be editable at all.

**Comment by appukuttan-shailesh** [comment]
Oh ok.... can't we enable editing as long as results haven't been created using it? ... same as for test_instances? Just in case some mistake was created while creating it?

tagging @HFragnaud

**Comment by apdavison** [comment]
yes, that makes sense
