### ISSUE TITLE
Invalid Hyperlink for Test Data Location URL

### ISSUE THREAD

**Issue by appukuttan-shailesh** [joffreygonin/hbp-validation-framework_dev#99]
The URL displayed on the test page for Data location is currently invalid.
For example, I enter the URL as: 
`collab://CA1 pyramidal cell validation/test_observations/feat_CA1_int_bAC.json` and the hyperlink created is for `https://validation-dev.brainsimulation.eu/url`

**Comment by appukuttan-shailesh** [comment]
p.s. the text on the hyperlink is OK, it is the hyperlink target URL which is incorrect.

**Comment by HFragnaud** [comment]
fixed in #102
